name: product-recommendation-system-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - ipykernel=6.29.4
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.0
  - scikit-surprise=1.1.4
  - seaborn=0.13.2
